<<<<<<< HEAD

# project_id = "jlzkwcgzpfrdgcdjmjao"

[process-payment]
verify_jwt = true

[process-transfer]
verify_jwt = true

[asaas-customer]
verify_jwt = true

[send-employee-invite]
verify_jwt = true

[asaas-webhook]
verify_jwt = false

[process-transfers-batch]
verify_jwt = true
=======
[functions.asaas-webhook]
verify_jwt=false 
>>>>>>> main
