
project_id = "jlzkwcgzpfrdgcdjmjao"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
name = "asaas-api"
verify_jwt = true

[[functions]]
name = "asaas-webhook"
verify_jwt = false
