
<<<<<<< HEAD
project_id = "jlzkwcgzpfrdgcdjmjao"

[functions.asaas-customer]
verify_jwt = true

[functions.process-transfer]
verify_jwt = true
=======
[functions.asaas-webhook]
verify_jwt = false
>>>>>>> main
