// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlzkwcgzpfrdgcdjmjao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impsemt3Y2d6cGZyZGdjZGptamFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzY5ODYsImV4cCI6MjA1MjU1Mjk4Nn0.jWqRJdpYYqrWAiFqXhSpA_Ry7rWPVmI4EGG-HBRlETw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);